version: '3.8'

services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SQS_QUEUE_NAME=order-events
    depends_on:
      - postgres
      - localstack
    networks:
      - hexagonal-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=hexagonal_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hexagonal-network

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/tmp/localstack
    networks:
      - hexagonal-network

volumes:
  postgres_data:
  localstack_data:

networks:
  hexagonal-network:
    driver: bridge
